# Generated by Django 4.1.2 on 2022-11-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Substance",
            fields=[
                ("PubChem_Name", models.CharField(max_length=50)),
                ("PubChem_alias", models.CharField(max_length=50)),
                ("PubChem_CID", models.IntegerField(primary_key=True, serialize=False)),
                ("PubChem_Mass", models.IntegerField()),
                ("PubChem_Formula", models.IntegerField()),
            ],
        ),
    ]
