# Generated by Django 4.1.3 on 2022-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Substance",
            fields=[
                ("PubChem_Name", models.CharField(max_length=50)),
                ("PubChem_Alias", models.CharField(max_length=50)),
                ("PubChem_CID", models.IntegerField(primary_key=True, serialize=False)),
                ("PubChem_Mass", models.FloatField()),
                ("PubChem_Formula", models.CharField(max_length=50)),
            ],
        ),
    ]
