# Generated by Django 4.1.3 on 2022-11-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Molecule",
            fields=[
                (
                    "inchi_key",
                    models.CharField(max_length=27, primary_key=True, serialize=False),
                ),
                ("log_p", models.FloatField(blank=True, default=None, null=True)),
                (
                    "num_h_acceptors",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "num_h_donors",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "molecular_mass",
                    models.FloatField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
