# Generated by Django 4.1.3 on 2022-12-07 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('inchi_key', models.CharField(max_length=27, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(27)])),
                ('log_p', models.FloatField(blank=True, default=None, null=True)),
                ('molecular_formula', models.CharField(blank=True, default=None, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('molecular_weight', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_h_acceptors', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('num_h_donors', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('num_rotatable_bonds', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('num_rings', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoleculeSet',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1)])),
                ('molecules', models.ManyToManyField(to='compounds.molecule')),
            ],
            options={
                'ordering': ['set_name'],
            },
        ),
    ]
