# Generated by Django 4.1.3 on 2022-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compounds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moleculeset",
            name="description",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
