# Generated by Django 4.1.3 on 2022-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(choices=[('inchi_key', 'inchi_key'), ('log_p', 'log_p'), ('molecular_formula', 'molecular_formula'), ('molecular_weight', 'molecular_weight'), ('num_h_acceptors', 'num_h_acceptors'), ('num_h_donors', 'num_h_donors'), ('num_rotatable_bonds', 'num_rotatable_bonds'), ('num_rings', 'num_rings')], max_length=20)),
            ],
        ),
    ]
